[pytest]
testpaths = tests
addopts = -v
filterwarnings =
    ignore:pkg_resources is deprecated:DeprecationWarning
    ignore:.*PySoundFile failed.*:UserWarning
    ignore:.*Deprecated as of librosa.*:FutureWarning
